export const APP_ROUTES = {
  root: '/',
  payloadAdmin: '/admin',
  internal: {
    base: '/internal',
    login: '/internal/login',
    dashboard: '/internal/dashboard',
    schedule: '/internal/schedule',
    settings: '/internal/settings',
    team: {
      base: '/internal/settings/team',
      addHolidayToCalendar: '/internal/settings/team/add-holiday-to-calendar',
      createCompensation: '/internal/settings/team/create-compensation',
      createHolidayCalendar: '/internal/settings/team/create-holiday-calendar',
      createShift: '/internal/settings/team/create-shift',
      createUser: '/internal/settings/team/create-user',
      deleteHolidayFromCalendar: '/internal/settings/team/delete-holiday-from-calendar',
      deleteShift: '/internal/settings/team/delete-shift',
      toggleActive: '/internal/settings/team/toggle-active',
    },
    hr: {
      analytics: '/internal/hr/analytics',
      attendance: '/internal/hr/attendance',
      attendancePunchIn: '/internal/hr/attendance/punch-in',
      attendancePunchOut: '/internal/hr/attendance/punch-out',
      leave: '/internal/hr/leave',
      leaveApply: '/internal/hr/leave/apply',
      leaveAction: '/internal/hr/leave/action',
      leaveApprove: '/internal/hr/leave/approve',
      leaveReject: '/internal/hr/leave/reject',
      performance: '/internal/hr/performance',
      performanceGenerate: '/internal/hr/performance/generate',
      performanceReview: '/internal/hr/performance/review',
      payroll: '/internal/hr/payroll',
      payrollGenerate: '/internal/hr/payroll/generate',
      payrollLock: '/internal/hr/payroll/lock',
      payrollApprove: '/internal/hr/payroll/approve',
      payrollDisburse: '/internal/hr/payroll/disburse',
    },
    assignments: {
      head: '/internal/assignments/head',
      lead: '/internal/assignments/lead',
    },
    jobs: {
      assigned: '/internal/jobs/assigned',
      create: '/internal/jobs/create',
      detailBase: '/internal/jobs/assigned',
      templates: '/internal/jobs/templates',
      templatesCreate: '/internal/jobs/templates/create',
    },
    clients: {
      create: '/internal/clients/create',
      detailBase: '/internal/clients',
      list: '/internal/clients',
    },
    candidates: {
      activityCreate: '/internal/candidates/activity/create',
      create: '/internal/candidates/create',
      detailBase: '/internal/candidates',
      list: '/internal/candidates',
      new: '/internal/candidates/new',
      parseResume: '/internal/candidates/parse-resume',
    },
    applications: {
      create: '/internal/applications/create',
      detailBase: '/internal/applications',
      list: '/internal/applications',
      new: '/internal/applications/new',
      review: '/internal/applications/review',
      reviewQueue: '/internal/applications/review-queue',
      stage: '/internal/applications/stage',
      submit: '/internal/applications/submit',
    },
    interviews: {
      create: '/internal/interviews/create',
      detailBase: '/internal/interviews',
      list: '/internal/interviews',
      updateStatus: '/internal/interviews/update-status',
    },
    placements: {
      create: '/internal/placements/create',
      detailBase: '/internal/placements',
      list: '/internal/placements',
      updateStatus: '/internal/placements/update-status',
    },
  },
  api: {
    internal: {
      hr: {
        analyticsSummary: '/api/internal/hr/analytics/summary',
        attendanceMe: '/api/internal/hr/attendance/me',
        attendancePunchIn: '/api/internal/hr/attendance/punch-in',
        attendancePunchOut: '/api/internal/hr/attendance/punch-out',
      },
    },
  },
  candidate: {
    base: '/candidate',
    inviteBase: '/candidate/invite',
    login: '/candidate/login',
    dashboard: '/candidate/dashboard',
    applications: '/candidate/applications',
  },
} as const

export const PAYLOAD_AUTH_COOKIE_NAME = 'payload-token'
