/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'candidate-users': CandidateUserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'candidate-users': CandidateUser;
    clients: Client;
    jobs: Job;
    'job-requests': JobRequest;
    'client-lead-assignments': ClientLeadAssignment;
    'job-lead-assignments': JobLeadAssignment;
    'recruiter-job-assignments': RecruiterJobAssignment;
    'candidate-resumes': CandidateResume;
    candidates: Candidate;
    'candidate-activities': CandidateActivity;
    applications: Application;
    'application-stage-history': ApplicationStageHistory;
    'candidate-invites': CandidateInvite;
    'job-templates': JobTemplate;
    interviews: Interview;
    placements: Placement;
    'employee-profiles': EmployeeProfile;
    'employee-compensation': EmployeeCompensation;
    'attendance-shifts': AttendanceShift;
    'holiday-calendars': HolidayCalendar;
    'attendance-logs': AttendanceLog;
    'attendance-daily-summaries': AttendanceDailySummary;
    'leave-types': LeaveType;
    'leave-balances': LeaveBalance;
    'leave-requests': LeaveRequest;
    'performance-cycles': PerformanceCycle;
    'performance-snapshots': PerformanceSnapshot;
    'performance-reviews': PerformanceReview;
    'payroll-rule-sets': PayrollRuleSet;
    'payroll-cycles': PayrollCycle;
    'payroll-runs': PayrollRun;
    'payroll-line-items': PayrollLineItem;
    payslips: Payslip;
    'payroll-payout-transactions': PayrollPayoutTransaction;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'candidate-users': CandidateUsersSelect<false> | CandidateUsersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'job-requests': JobRequestsSelect<false> | JobRequestsSelect<true>;
    'client-lead-assignments': ClientLeadAssignmentsSelect<false> | ClientLeadAssignmentsSelect<true>;
    'job-lead-assignments': JobLeadAssignmentsSelect<false> | JobLeadAssignmentsSelect<true>;
    'recruiter-job-assignments': RecruiterJobAssignmentsSelect<false> | RecruiterJobAssignmentsSelect<true>;
    'candidate-resumes': CandidateResumesSelect<false> | CandidateResumesSelect<true>;
    candidates: CandidatesSelect<false> | CandidatesSelect<true>;
    'candidate-activities': CandidateActivitiesSelect<false> | CandidateActivitiesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'application-stage-history': ApplicationStageHistorySelect<false> | ApplicationStageHistorySelect<true>;
    'candidate-invites': CandidateInvitesSelect<false> | CandidateInvitesSelect<true>;
    'job-templates': JobTemplatesSelect<false> | JobTemplatesSelect<true>;
    interviews: InterviewsSelect<false> | InterviewsSelect<true>;
    placements: PlacementsSelect<false> | PlacementsSelect<true>;
    'employee-profiles': EmployeeProfilesSelect<false> | EmployeeProfilesSelect<true>;
    'employee-compensation': EmployeeCompensationSelect<false> | EmployeeCompensationSelect<true>;
    'attendance-shifts': AttendanceShiftsSelect<false> | AttendanceShiftsSelect<true>;
    'holiday-calendars': HolidayCalendarsSelect<false> | HolidayCalendarsSelect<true>;
    'attendance-logs': AttendanceLogsSelect<false> | AttendanceLogsSelect<true>;
    'attendance-daily-summaries': AttendanceDailySummariesSelect<false> | AttendanceDailySummariesSelect<true>;
    'leave-types': LeaveTypesSelect<false> | LeaveTypesSelect<true>;
    'leave-balances': LeaveBalancesSelect<false> | LeaveBalancesSelect<true>;
    'leave-requests': LeaveRequestsSelect<false> | LeaveRequestsSelect<true>;
    'performance-cycles': PerformanceCyclesSelect<false> | PerformanceCyclesSelect<true>;
    'performance-snapshots': PerformanceSnapshotsSelect<false> | PerformanceSnapshotsSelect<true>;
    'performance-reviews': PerformanceReviewsSelect<false> | PerformanceReviewsSelect<true>;
    'payroll-rule-sets': PayrollRuleSetsSelect<false> | PayrollRuleSetsSelect<true>;
    'payroll-cycles': PayrollCyclesSelect<false> | PayrollCyclesSelect<true>;
    'payroll-runs': PayrollRunsSelect<false> | PayrollRunsSelect<true>;
    'payroll-line-items': PayrollLineItemsSelect<false> | PayrollLineItemsSelect<true>;
    payslips: PayslipsSelect<false> | PayslipsSelect<true>;
    'payroll-payout-transactions': PayrollPayoutTransactionsSelect<false> | PayrollPayoutTransactionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | CandidateUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CandidateUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName?: string | null;
  role: 'admin' | 'leadRecruiter' | 'recruiter';
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-users".
 */
export interface CandidateUser {
  id: number;
  fullName: string;
  role: 'candidate';
  candidateProfile: number | Candidate;
  isActive: boolean;
  onboardingMethod: 'password' | 'magicLink' | 'oauth';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'candidate-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidates".
 */
export interface Candidate {
  id: number;
  candidateCode?: string | null;
  prefix?: string | null;
  firstName?: string | null;
  middleName?: string | null;
  lastName?: string | null;
  nickName?: string | null;
  fullName: string;
  email?: string | null;
  alternateEmail?: string | null;
  phone?: string | null;
  alternatePhone?: string | null;
  homePhone?: string | null;
  workPhone?: string | null;
  otherPhone?: string | null;
  skypeID?: string | null;
  facebookProfileURL?: string | null;
  twitterProfileURL?: string | null;
  videoReference?: string | null;
  currentLocation?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  postalCode?: string | null;
  address?: string | null;
  totalExperienceYears?: number | null;
  totalExperienceMonths?: number | null;
  currentCompany?: string | null;
  jobTitle?: string | null;
  currentRole?: string | null;
  skills?: string[] | null;
  primarySkills?: string[] | null;
  technology?: string | null;
  expectedSalary?: number | null;
  expectedPayMin?: number | null;
  expectedPayMax?: number | null;
  expectedPayCurrency?: string | null;
  expectedPayType?: string | null;
  expectedPayUnit?: string | null;
  noticePeriodDays?: number | null;
  noticePeriodLabel?: string | null;
  relocation?: boolean | null;
  taxTerms?: string | null;
  gpa?: string | null;
  nationality?: string | null;
  aadhaarNumber?: string | null;
  referenceID?: string | null;
  referredBy?: string | null;
  applicantStatus?: string | null;
  applicantGroup?: string | null;
  ownership?: (number | null) | User;
  workAuthorization?: string | null;
  workAuthorizationExpiry?: string | null;
  clearance?: boolean | null;
  gender?: string | null;
  raceEthnicity?: string | null;
  veteranStatus?: string | null;
  disabilityStatus?: string | null;
  technicalSkillsRating?: number | null;
  communicationSkillsRating?: number | null;
  professionalismRating?: number | null;
  overallRating?: number | null;
  source: 'naukri' | 'linkedin' | 'reference' | 'careerPortal' | 'walkIn' | 'consultancy' | 'database' | 'other';
  sourceDetails?: string | null;
  resume?: (number | null) | CandidateResume;
  linkedInURL?: string | null;
  portfolioURL?: string | null;
  sourceJob: number | Job;
  sourcedBy?: (number | null) | User;
  candidateAccount?: (number | null) | CandidateUser;
  profileCompletedAt?: string | null;
  notes?: string | null;
  additionalComments?: string | null;
  educationDetails?:
    | {
        degree?: string | null;
        institution?: string | null;
        location?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        id?: string | null;
      }[]
    | null;
  certifications?:
    | {
        name?: string | null;
        issuer?: string | null;
        credentialID?: string | null;
        issueDate?: string | null;
        expiryDate?: string | null;
        id?: string | null;
      }[]
    | null;
  workExperience?:
    | {
        employer?: string | null;
        title?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        isCurrent?: boolean | null;
        summary?: string | null;
        id?: string | null;
      }[]
    | null;
  employerDetails?:
    | {
        employerName?: string | null;
        contactName?: string | null;
        contactEmail?: string | null;
        contactPhone?: string | null;
        designation?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        reasonForLeaving?: string | null;
        id?: string | null;
      }[]
    | null;
  employmentTestResults?:
    | {
        testName?: string | null;
        score?: number | null;
        maxScore?: number | null;
        result?: string | null;
        completedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        language?: string | null;
        canRead?: boolean | null;
        canWrite?: boolean | null;
        canSpeak?: boolean | null;
        id?: string | null;
      }[]
    | null;
  normalizedEmail?: string | null;
  normalizedPhone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-resumes".
 */
export interface CandidateResume {
  id: number;
  alt: string;
  sourceJob: number | Job;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  jobCode?: string | null;
  client: number | Client;
  title: string;
  requisitionTitle?: string | null;
  businessUnit?: string | null;
  clientJobID?: string | null;
  department?: string | null;
  employmentType: 'fullTime' | 'partTime' | 'contract' | 'internship';
  location?: string | null;
  states?: string[] | null;
  clientBillRate?: string | null;
  payRate?: string | null;
  payType?: string | null;
  salaryRangeLabel?: string | null;
  salaryMin?: number | null;
  salaryMax?: number | null;
  experienceMin?: number | null;
  experienceMax?: number | null;
  openings: number;
  description: string;
  requiredSkills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'active' | 'onHold' | 'closed' | 'inactive';
  targetClosureDate?: string | null;
  requirementAssignedOn?: string | null;
  createdBy?: (number | null) | User;
  recruitmentManager?: (number | null) | User;
  primaryRecruiter?: (number | null) | User;
  assignedTo?: (number | User)[] | null;
  /**
   * Lead recruiter owning execution for this job.
   */
  owningHeadRecruiter: number | User;
  sourceJobRequest?: (number | null) | JobRequest;
  dedupeKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  clientCode?: string | null;
  name: string;
  logo?: (number | null) | Media;
  contactPerson: string;
  email: string;
  phone: string;
  industry?: string | null;
  category?: string | null;
  primaryBusinessUnit?: string | null;
  businessUnits?: string[] | null;
  clientVisibilityLevel?: ('organization' | 'businessUnit') | null;
  vmsClientName?: string | null;
  federalID?: string | null;
  location?: string | null;
  website?: string | null;
  companySize?: ('1-50' | '51-200' | '201-1000' | '1000+') | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  postalCode?: string | null;
  fax?: string | null;
  billingTerms?: string | null;
  paymentTerms?: string | null;
  practice?: string | null;
  status: 'active' | 'inactive';
  /**
   * Optional primary lead owner. Admin can still assign multiple leads separately.
   */
  owningHeadRecruiter?: (number | null) | User;
  primaryOwner?: (number | null) | User;
  ownership?: (number | null) | User;
  clientLead?: (number | null) | User;
  requiredDocuments?: ('msa' | 'nda' | 'sow' | 'complianceCertificate')[] | null;
  clientShortName?: string | null;
  aboutCompany?: string | null;
  sendRequirement?: boolean | null;
  sendHotlist?: boolean | null;
  allowAccessToAllUsers?: boolean | null;
  displayOnJob?: boolean | null;
  stopContactNotification?: boolean | null;
  defaultJobAddress?: boolean | null;
  notes?: string | null;
  normalizedName?: string | null;
  normalizedEmail?: string | null;
  normalizedPhone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-requests".
 */
export interface JobRequest {
  id: number;
  jobRequestCode?: string | null;
  intakeSource: 'email' | 'phone' | 'portal' | 'manual';
  subject: string;
  message: string;
  client?: (number | null) | Client;
  /**
   * Use when client does not exist yet in the clients master.
   */
  clientName?: string | null;
  contactPerson?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  proposedTitle?: string | null;
  proposedDepartment?: string | null;
  proposedEmploymentType?: ('fullTime' | 'partTime' | 'contract' | 'internship') | null;
  proposedLocation?: string | null;
  proposedSalaryMin?: number | null;
  proposedSalaryMax?: number | null;
  proposedExperienceMin?: number | null;
  proposedExperienceMax?: number | null;
  proposedOpenings?: number | null;
  proposedDescription?: string | null;
  proposedRequiredSkills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  priority?: ('low' | 'medium' | 'high' | 'urgent') | null;
  status: 'new' | 'underReview' | 'approved' | 'rejected' | 'converted' | 'duplicateActive' | 'reactivated';
  linkedJob?: (number | null) | Job;
  owningHeadRecruiter?: (number | null) | User;
  receivedAt: string;
  processedBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-lead-assignments".
 */
export interface ClientLeadAssignment {
  id: number;
  client: number | Client;
  /**
   * Admin owner for this assignment row.
   */
  headRecruiter: number | User;
  leadRecruiter: number | User;
  status: 'active' | 'inactive';
  assignedBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-lead-assignments".
 */
export interface JobLeadAssignment {
  id: number;
  client: number | Client;
  job: number | Job;
  /**
   * Admin owner for this assignment row.
   */
  headRecruiter: number | User;
  leadRecruiter: number | User;
  status: 'active' | 'inactive';
  assignedBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruiter-job-assignments".
 */
export interface RecruiterJobAssignment {
  id: number;
  job: number | Job;
  leadRecruiter: number | User;
  recruiter: number | User;
  status: 'active' | 'inactive';
  assignedBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-activities".
 */
export interface CandidateActivity {
  id: number;
  activityCode?: string | null;
  candidate: number | Candidate;
  application?: (number | null) | Application;
  type: 'note' | 'task' | 'message' | 'activity';
  title: string;
  description?: string | null;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'open' | 'inProgress' | 'completed' | 'cancelled';
  actionRequired?: string | null;
  dueAt?: string | null;
  timezone?: string | null;
  assignedTo?: (number | null) | User;
  createdBy?: (number | null) | User;
  modifiedOn?: string | null;
  statusModifiedOn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  applicationCode?: string | null;
  candidate: number | Candidate;
  job: number | Job;
  recruiter: number | User;
  candidateAccount?: (number | null) | CandidateUser;
  stage:
    | 'sourced'
    | 'screened'
    | 'submittedToClient'
    | 'interviewScheduled'
    | 'interviewCleared'
    | 'offerReleased'
    | 'joined'
    | 'rejected';
  notes?: string | null;
  latestComment?: string | null;
  pipelineSource?: string | null;
  submissionType?: string | null;
  clientBillRate?: string | null;
  payRate?: string | null;
  submittedAt?: string | null;
  sourcedAt?: string | null;
  screenedAt?: string | null;
  submittedToClientAt?: string | null;
  interviewScheduledAt?: string | null;
  interviewClearedAt?: string | null;
  offerReleasedAt?: string | null;
  joinedAt?: string | null;
  rejectedAt?: string | null;
  clientSubmittedAt?: string | null;
  interviewAt?: string | null;
  confirmedAt?: string | null;
  placedAt?: string | null;
  notJoinedAt?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  candidateInvitedAt?: string | null;
  candidateAppliedAt?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application-stage-history".
 */
export interface ApplicationStageHistory {
  id: number;
  application: number | Application;
  candidate: number | Candidate;
  candidateAccount?: (number | null) | CandidateUser;
  job: number | Job;
  recruiter: number | User;
  fromStage?:
    | (
        | 'sourced'
        | 'screened'
        | 'submittedToClient'
        | 'interviewScheduled'
        | 'interviewCleared'
        | 'offerReleased'
        | 'joined'
        | 'rejected'
      )
    | null;
  toStage:
    | 'sourced'
    | 'screened'
    | 'submittedToClient'
    | 'interviewScheduled'
    | 'interviewCleared'
    | 'offerReleased'
    | 'joined'
    | 'rejected';
  comment?: string | null;
  actor?: (number | null) | User;
  changedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-invites".
 */
export interface CandidateInvite {
  id: number;
  candidate: number | Candidate;
  application: number | Application;
  inviteEmail: string;
  tokenHash: string;
  status: 'pending' | 'consumed' | 'expired' | 'revoked';
  expiresAt: string;
  sentAt: string;
  sentBy?: (number | null) | User;
  consumedAt?: string | null;
  revokedAt?: string | null;
  accountAccessSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-templates".
 */
export interface JobTemplate {
  id: number;
  templateCode?: string | null;
  templateName: string;
  title: string;
  requisitionTitle?: string | null;
  department?: string | null;
  businessUnit?: string | null;
  employmentType: 'fullTime' | 'partTime' | 'contract' | 'internship';
  location?: string | null;
  states?: string[] | null;
  salaryMin?: number | null;
  salaryMax?: number | null;
  experienceMin?: number | null;
  experienceMax?: number | null;
  openings?: number | null;
  description: string;
  requiredSkills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  isActive?: boolean | null;
  ownedByLeadRecruiter?: (number | null) | User;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interviews".
 */
export interface Interview {
  id: number;
  interviewCode?: string | null;
  application: number | Application;
  candidate?: (number | null) | Candidate;
  job?: (number | null) | Job;
  recruiter?: (number | null) | User;
  client?: (number | null) | Client;
  interviewRound: 'screening' | 'technicalRound1' | 'technicalRound2' | 'managerial' | 'hr' | 'final';
  interviewTemplate?: string | null;
  interviewerName: string;
  interviewerEmail?: string | null;
  clientPOC?: string | null;
  mode: 'video' | 'inPerson' | 'phone';
  meetingLink?: string | null;
  location?: string | null;
  timezone?: string | null;
  startTime: string;
  endTime: string;
  status: 'scheduled' | 'rescheduled' | 'completed' | 'cancelled' | 'noShow';
  initiatedBy?: (number | null) | User;
  initiatedOn?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placements".
 */
export interface Placement {
  id: number;
  placementCode?: string | null;
  application: number | Application;
  candidate?: (number | null) | Candidate;
  job?: (number | null) | Job;
  recruiter?: (number | null) | User;
  client?: (number | null) | Client;
  placementType: 'recurringRevenue' | 'oneTimeRevenue' | 'inHouse';
  clientPrimeVendor?: string | null;
  businessUnit?: string | null;
  clientBillRate?: string | null;
  payRate?: string | null;
  perDiemPerHour?: string | null;
  overhead?: string | null;
  margin?: string | null;
  tentativeStartDate?: string | null;
  actualStartDate?: string | null;
  actualEndDate?: string | null;
  projectDurationDays?: number | null;
  status: 'active' | 'inactive' | 'completed' | 'cancelled';
  createdBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-profiles".
 */
export interface EmployeeProfile {
  id: number;
  employeeCode?: string | null;
  user: number | User;
  dateOfJoining: string;
  employmentStatus: 'active' | 'inactive' | 'onNotice' | 'terminated';
  designation: string;
  department?: string | null;
  workLocation: string;
  workState: string;
  workCountry?: string | null;
  reportingManager?: (number | null) | User;
  attendanceShift?: (number | null) | AttendanceShift;
  holidayCalendar?: (number | null) | HolidayCalendar;
  weeklyOffDays?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[] | null;
  isPayrollEligible?: boolean | null;
  payoutReady?: boolean | null;
  panNumber?: string | null;
  aadhaarNumber?: string | null;
  uanNumber?: string | null;
  esicNumber?: string | null;
  bankAccountName?: string | null;
  bankAccountNumber?: string | null;
  bankIFSC?: string | null;
  bankName?: string | null;
  razorpayContactID?: string | null;
  razorpayFundAccountID?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance-shifts".
 */
export interface AttendanceShift {
  id: number;
  shiftCode?: string | null;
  name: string;
  shiftStartTime: string;
  shiftEndTime: string;
  graceMinutes: number;
  halfDayThresholdMinutes: number;
  fullDayThresholdMinutes: number;
  overtimeThresholdMinutes: number;
  weeklyOffDays: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
  isDefault?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holiday-calendars".
 */
export interface HolidayCalendar {
  id: number;
  calendarCode?: string | null;
  name: string;
  state: string;
  year: number;
  holidays?:
    | {
        name: string;
        date: string;
        type: 'national' | 'festival' | 'company';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-compensation".
 */
export interface EmployeeCompensation {
  id: number;
  compensationCode?: string | null;
  employee: number | EmployeeProfile;
  effectiveFrom: string;
  effectiveTo?: string | null;
  annualCTC: number;
  monthlyGross: number;
  basicMonthly: number;
  hraMonthly?: number | null;
  specialAllowanceMonthly?: number | null;
  otherAllowanceMonthly?: number | null;
  variableMonthly?: number | null;
  reimbursementMonthly?: number | null;
  customEarnings?:
    | {
        label: string;
        amount: number;
        id?: string | null;
      }[]
    | null;
  customDeductions?:
    | {
        label: string;
        amount: number;
        id?: string | null;
      }[]
    | null;
  taxRegime: 'old' | 'new';
  pfEnabled?: boolean | null;
  esiEnabled?: boolean | null;
  professionalTaxEnabled?: boolean | null;
  lwfEnabled?: boolean | null;
  tdsEnabled?: boolean | null;
  isActive?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance-logs".
 */
export interface AttendanceLog {
  id: number;
  attendanceLogCode?: string | null;
  employee: number | EmployeeProfile;
  punchDate: string;
  punchInAt: string;
  punchOutAt?: string | null;
  source: 'web' | 'mobileWeb';
  ipAddress?: string | null;
  deviceInfo?: string | null;
  geoLatitude?: number | null;
  geoLongitude?: number | null;
  tamperFlags?: string[] | null;
  workedMinutes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance-daily-summaries".
 */
export interface AttendanceDailySummary {
  id: number;
  summaryCode?: string | null;
  employee: number | EmployeeProfile;
  date: string;
  status: 'present' | 'absent' | 'halfDay' | 'leave' | 'holiday' | 'weekOff';
  workedMinutes?: number | null;
  lateMinutes?: number | null;
  overtimeMinutes?: number | null;
  lop?: boolean | null;
  holidayName?: string | null;
  attendanceLog?: (number | null) | AttendanceLog;
  leaveRequest?: (number | null) | LeaveRequest;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leave-requests".
 */
export interface LeaveRequest {
  id: number;
  leaveRequestCode?: string | null;
  employee: number | EmployeeProfile;
  employeeRole?: string | null;
  leaveType: number | LeaveType;
  leaveUnit: 'fullDay' | 'halfDay';
  startDate: string;
  endDate: string;
  totalDays: number;
  reason: string;
  status: 'pendingLeadApproval' | 'pendingAdminApproval' | 'approved' | 'rejected' | 'cancelled';
  requestedBy?: (number | null) | User;
  leadApprover?: (number | null) | User;
  adminApprover?: (number | null) | User;
  leadDecisionAt?: string | null;
  adminDecisionAt?: string | null;
  rejectionReason?: string | null;
  comments?: string | null;
  workflowTrail?:
    | {
        action: 'apply' | 'leadApprove' | 'adminApprove' | 'adminOverrideApprove' | 'reject' | 'cancel';
        fromStatus?: ('pendingLeadApproval' | 'pendingAdminApproval' | 'approved' | 'rejected' | 'cancelled') | null;
        toStatus: 'pendingLeadApproval' | 'pendingAdminApproval' | 'approved' | 'rejected' | 'cancelled';
        comment?: string | null;
        overrideReason?: string | null;
        actedBy?: (number | null) | User;
        actedAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leave-types".
 */
export interface LeaveType {
  id: number;
  leaveTypeCode?: string | null;
  key: 'CL' | 'SL' | 'EL';
  name: string;
  paid?: boolean | null;
  accrualPerMonth: number;
  annualAllowance: number;
  carryForwardLimit: number;
  isEncashable?: boolean | null;
  minUnit: 'fullDay' | 'halfDay';
  maxConsecutiveDays: number;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leave-balances".
 */
export interface LeaveBalance {
  id: number;
  balanceCode?: string | null;
  employee: number | EmployeeProfile;
  leaveType: number | LeaveType;
  year: number;
  openingBalance: number;
  accrued: number;
  used: number;
  adjustments: number;
  closingBalance: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance-cycles".
 */
export interface PerformanceCycle {
  id: number;
  cycleCode?: string | null;
  title: string;
  month: number;
  year: number;
  startDate: string;
  endDate: string;
  kpiWeight: number;
  managerWeight: number;
  status: 'open' | 'closed' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance-snapshots".
 */
export interface PerformanceSnapshot {
  id: number;
  snapshotCode?: string | null;
  cycle: number | PerformanceCycle;
  employee: number | EmployeeProfile;
  generatedBy?: (number | null) | User;
  generatedAt?: string | null;
  submissionsCount?: number | null;
  approvalsCount?: number | null;
  rejectionCount?: number | null;
  interviewCount?: number | null;
  placementCount?: number | null;
  avgTurnaroundHours?: number | null;
  slaBreachesCount?: number | null;
  kpiScore?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance-reviews".
 */
export interface PerformanceReview {
  id: number;
  reviewCode?: string | null;
  cycle: number | PerformanceCycle;
  employee: number | EmployeeProfile;
  reviewer: number | User;
  managerRating: number;
  managerComments?: string | null;
  kpiScore?: number | null;
  finalScore?: number | null;
  status: 'draft' | 'submitted' | 'finalized';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-rule-sets".
 */
export interface PayrollRuleSet {
  id: number;
  ruleSetCode?: string | null;
  name: string;
  state: string;
  effectiveFrom: string;
  effectiveTo?: string | null;
  isActive?: boolean | null;
  pfEnabled?: boolean | null;
  pfEmployeeRate?: number | null;
  pfEmployerRate?: number | null;
  pfWageCap?: number | null;
  esiEnabled?: boolean | null;
  esiEmployeeRate?: number | null;
  esiEmployerRate?: number | null;
  esiWageThreshold?: number | null;
  professionalTaxEnabled?: boolean | null;
  professionalTaxMonthly?: number | null;
  lwfEnabled?: boolean | null;
  lwfEmployeeMonthly?: number | null;
  lwfEmployerMonthly?: number | null;
  tdsEnabled?: boolean | null;
  tdsRate?: number | null;
  standardDeductionMonthly?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-cycles".
 */
export interface PayrollCycle {
  id: number;
  payrollCycleCode?: string | null;
  title?: string | null;
  month: number;
  year: number;
  startDate: string;
  endDate: string;
  payoutDate?: string | null;
  status: 'draft' | 'open' | 'closed';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-runs".
 */
export interface PayrollRun {
  id: number;
  payrollRunCode?: string | null;
  payrollCycle: number | PayrollCycle;
  ruleSet?: (number | null) | PayrollRuleSet;
  status: 'draft' | 'locked' | 'approved' | 'disbursing' | 'completed' | 'failed' | 'cancelled';
  preparedBy?: (number | null) | User;
  preparedAt?: string | null;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  disbursedBy?: (number | null) | User;
  disbursedAt?: string | null;
  totalEmployees?: number | null;
  totalGross?: number | null;
  totalDeductions?: number | null;
  totalNet?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-line-items".
 */
export interface PayrollLineItem {
  id: number;
  payrollLineItemCode?: string | null;
  payrollRun: number | PayrollRun;
  employee: number | EmployeeProfile;
  compensation?: (number | null) | EmployeeCompensation;
  grossEarnings: number;
  totalDeductions: number;
  netPayable: number;
  lopDays?: number | null;
  lopDeduction?: number | null;
  pfEmployee?: number | null;
  pfEmployer?: number | null;
  esiEmployee?: number | null;
  esiEmployer?: number | null;
  professionalTax?: number | null;
  lwfEmployee?: number | null;
  lwfEmployer?: number | null;
  tds?: number | null;
  reimbursementTotal?: number | null;
  customEarningsTotal?: number | null;
  customDeductionsTotal?: number | null;
  earningsBreakdown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  deductionsBreakdown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'created' | 'processing' | 'processed' | 'failed' | 'reversed' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payslips".
 */
export interface Payslip {
  id: number;
  payslipCode?: string | null;
  employee: number | EmployeeProfile;
  payrollRun: number | PayrollRun;
  payrollLineItem?: (number | null) | PayrollLineItem;
  month: number;
  year: number;
  issueDate: string;
  pdfURL?: string | null;
  snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'generated' | 'published' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-payout-transactions".
 */
export interface PayrollPayoutTransaction {
  id: number;
  payoutTxnCode?: string | null;
  payrollRun: number | PayrollRun;
  lineItem: number | PayrollLineItem;
  employee: number | EmployeeProfile;
  provider?: string | null;
  payoutStatus: 'created' | 'processing' | 'processed' | 'failed' | 'reversed' | 'cancelled';
  payoutID?: string | null;
  idempotencyKey: string;
  attemptCount: number;
  utr?: string | null;
  responseLog?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorMessage?: string | null;
  webhookEventID?: string | null;
  initiatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'candidate-users';
        value: number | CandidateUser;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'job-requests';
        value: number | JobRequest;
      } | null)
    | ({
        relationTo: 'client-lead-assignments';
        value: number | ClientLeadAssignment;
      } | null)
    | ({
        relationTo: 'job-lead-assignments';
        value: number | JobLeadAssignment;
      } | null)
    | ({
        relationTo: 'recruiter-job-assignments';
        value: number | RecruiterJobAssignment;
      } | null)
    | ({
        relationTo: 'candidate-resumes';
        value: number | CandidateResume;
      } | null)
    | ({
        relationTo: 'candidates';
        value: number | Candidate;
      } | null)
    | ({
        relationTo: 'candidate-activities';
        value: number | CandidateActivity;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'application-stage-history';
        value: number | ApplicationStageHistory;
      } | null)
    | ({
        relationTo: 'candidate-invites';
        value: number | CandidateInvite;
      } | null)
    | ({
        relationTo: 'job-templates';
        value: number | JobTemplate;
      } | null)
    | ({
        relationTo: 'interviews';
        value: number | Interview;
      } | null)
    | ({
        relationTo: 'placements';
        value: number | Placement;
      } | null)
    | ({
        relationTo: 'employee-profiles';
        value: number | EmployeeProfile;
      } | null)
    | ({
        relationTo: 'employee-compensation';
        value: number | EmployeeCompensation;
      } | null)
    | ({
        relationTo: 'attendance-shifts';
        value: number | AttendanceShift;
      } | null)
    | ({
        relationTo: 'holiday-calendars';
        value: number | HolidayCalendar;
      } | null)
    | ({
        relationTo: 'attendance-logs';
        value: number | AttendanceLog;
      } | null)
    | ({
        relationTo: 'attendance-daily-summaries';
        value: number | AttendanceDailySummary;
      } | null)
    | ({
        relationTo: 'leave-types';
        value: number | LeaveType;
      } | null)
    | ({
        relationTo: 'leave-balances';
        value: number | LeaveBalance;
      } | null)
    | ({
        relationTo: 'leave-requests';
        value: number | LeaveRequest;
      } | null)
    | ({
        relationTo: 'performance-cycles';
        value: number | PerformanceCycle;
      } | null)
    | ({
        relationTo: 'performance-snapshots';
        value: number | PerformanceSnapshot;
      } | null)
    | ({
        relationTo: 'performance-reviews';
        value: number | PerformanceReview;
      } | null)
    | ({
        relationTo: 'payroll-rule-sets';
        value: number | PayrollRuleSet;
      } | null)
    | ({
        relationTo: 'payroll-cycles';
        value: number | PayrollCycle;
      } | null)
    | ({
        relationTo: 'payroll-runs';
        value: number | PayrollRun;
      } | null)
    | ({
        relationTo: 'payroll-line-items';
        value: number | PayrollLineItem;
      } | null)
    | ({
        relationTo: 'payslips';
        value: number | Payslip;
      } | null)
    | ({
        relationTo: 'payroll-payout-transactions';
        value: number | PayrollPayoutTransaction;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'candidate-users';
        value: number | CandidateUser;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'candidate-users';
        value: number | CandidateUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-users_select".
 */
export interface CandidateUsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  candidateProfile?: T;
  isActive?: T;
  onboardingMethod?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  clientCode?: T;
  name?: T;
  logo?: T;
  contactPerson?: T;
  email?: T;
  phone?: T;
  industry?: T;
  category?: T;
  primaryBusinessUnit?: T;
  businessUnits?: T;
  clientVisibilityLevel?: T;
  vmsClientName?: T;
  federalID?: T;
  location?: T;
  website?: T;
  companySize?: T;
  address?: T;
  city?: T;
  state?: T;
  country?: T;
  postalCode?: T;
  fax?: T;
  billingTerms?: T;
  paymentTerms?: T;
  practice?: T;
  status?: T;
  owningHeadRecruiter?: T;
  primaryOwner?: T;
  ownership?: T;
  clientLead?: T;
  requiredDocuments?: T;
  clientShortName?: T;
  aboutCompany?: T;
  sendRequirement?: T;
  sendHotlist?: T;
  allowAccessToAllUsers?: T;
  displayOnJob?: T;
  stopContactNotification?: T;
  defaultJobAddress?: T;
  notes?: T;
  normalizedName?: T;
  normalizedEmail?: T;
  normalizedPhone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  jobCode?: T;
  client?: T;
  title?: T;
  requisitionTitle?: T;
  businessUnit?: T;
  clientJobID?: T;
  department?: T;
  employmentType?: T;
  location?: T;
  states?: T;
  clientBillRate?: T;
  payRate?: T;
  payType?: T;
  salaryRangeLabel?: T;
  salaryMin?: T;
  salaryMax?: T;
  experienceMin?: T;
  experienceMax?: T;
  openings?: T;
  description?: T;
  requiredSkills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  priority?: T;
  status?: T;
  targetClosureDate?: T;
  requirementAssignedOn?: T;
  createdBy?: T;
  recruitmentManager?: T;
  primaryRecruiter?: T;
  assignedTo?: T;
  owningHeadRecruiter?: T;
  sourceJobRequest?: T;
  dedupeKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-requests_select".
 */
export interface JobRequestsSelect<T extends boolean = true> {
  jobRequestCode?: T;
  intakeSource?: T;
  subject?: T;
  message?: T;
  client?: T;
  clientName?: T;
  contactPerson?: T;
  contactEmail?: T;
  contactPhone?: T;
  proposedTitle?: T;
  proposedDepartment?: T;
  proposedEmploymentType?: T;
  proposedLocation?: T;
  proposedSalaryMin?: T;
  proposedSalaryMax?: T;
  proposedExperienceMin?: T;
  proposedExperienceMax?: T;
  proposedOpenings?: T;
  proposedDescription?: T;
  proposedRequiredSkills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  priority?: T;
  status?: T;
  linkedJob?: T;
  owningHeadRecruiter?: T;
  receivedAt?: T;
  processedBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-lead-assignments_select".
 */
export interface ClientLeadAssignmentsSelect<T extends boolean = true> {
  client?: T;
  headRecruiter?: T;
  leadRecruiter?: T;
  status?: T;
  assignedBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-lead-assignments_select".
 */
export interface JobLeadAssignmentsSelect<T extends boolean = true> {
  client?: T;
  job?: T;
  headRecruiter?: T;
  leadRecruiter?: T;
  status?: T;
  assignedBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruiter-job-assignments_select".
 */
export interface RecruiterJobAssignmentsSelect<T extends boolean = true> {
  job?: T;
  leadRecruiter?: T;
  recruiter?: T;
  status?: T;
  assignedBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-resumes_select".
 */
export interface CandidateResumesSelect<T extends boolean = true> {
  alt?: T;
  sourceJob?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidates_select".
 */
export interface CandidatesSelect<T extends boolean = true> {
  candidateCode?: T;
  prefix?: T;
  firstName?: T;
  middleName?: T;
  lastName?: T;
  nickName?: T;
  fullName?: T;
  email?: T;
  alternateEmail?: T;
  phone?: T;
  alternatePhone?: T;
  homePhone?: T;
  workPhone?: T;
  otherPhone?: T;
  skypeID?: T;
  facebookProfileURL?: T;
  twitterProfileURL?: T;
  videoReference?: T;
  currentLocation?: T;
  city?: T;
  state?: T;
  country?: T;
  postalCode?: T;
  address?: T;
  totalExperienceYears?: T;
  totalExperienceMonths?: T;
  currentCompany?: T;
  jobTitle?: T;
  currentRole?: T;
  skills?: T;
  primarySkills?: T;
  technology?: T;
  expectedSalary?: T;
  expectedPayMin?: T;
  expectedPayMax?: T;
  expectedPayCurrency?: T;
  expectedPayType?: T;
  expectedPayUnit?: T;
  noticePeriodDays?: T;
  noticePeriodLabel?: T;
  relocation?: T;
  taxTerms?: T;
  gpa?: T;
  nationality?: T;
  aadhaarNumber?: T;
  referenceID?: T;
  referredBy?: T;
  applicantStatus?: T;
  applicantGroup?: T;
  ownership?: T;
  workAuthorization?: T;
  workAuthorizationExpiry?: T;
  clearance?: T;
  gender?: T;
  raceEthnicity?: T;
  veteranStatus?: T;
  disabilityStatus?: T;
  technicalSkillsRating?: T;
  communicationSkillsRating?: T;
  professionalismRating?: T;
  overallRating?: T;
  source?: T;
  sourceDetails?: T;
  resume?: T;
  linkedInURL?: T;
  portfolioURL?: T;
  sourceJob?: T;
  sourcedBy?: T;
  candidateAccount?: T;
  profileCompletedAt?: T;
  notes?: T;
  additionalComments?: T;
  educationDetails?:
    | T
    | {
        degree?: T;
        institution?: T;
        location?: T;
        startDate?: T;
        endDate?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        issuer?: T;
        credentialID?: T;
        issueDate?: T;
        expiryDate?: T;
        id?: T;
      };
  workExperience?:
    | T
    | {
        employer?: T;
        title?: T;
        startDate?: T;
        endDate?: T;
        isCurrent?: T;
        summary?: T;
        id?: T;
      };
  employerDetails?:
    | T
    | {
        employerName?: T;
        contactName?: T;
        contactEmail?: T;
        contactPhone?: T;
        designation?: T;
        startDate?: T;
        endDate?: T;
        reasonForLeaving?: T;
        id?: T;
      };
  employmentTestResults?:
    | T
    | {
        testName?: T;
        score?: T;
        maxScore?: T;
        result?: T;
        completedAt?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        canRead?: T;
        canWrite?: T;
        canSpeak?: T;
        id?: T;
      };
  normalizedEmail?: T;
  normalizedPhone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-activities_select".
 */
export interface CandidateActivitiesSelect<T extends boolean = true> {
  activityCode?: T;
  candidate?: T;
  application?: T;
  type?: T;
  title?: T;
  description?: T;
  priority?: T;
  status?: T;
  actionRequired?: T;
  dueAt?: T;
  timezone?: T;
  assignedTo?: T;
  createdBy?: T;
  modifiedOn?: T;
  statusModifiedOn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  applicationCode?: T;
  candidate?: T;
  job?: T;
  recruiter?: T;
  candidateAccount?: T;
  stage?: T;
  notes?: T;
  latestComment?: T;
  pipelineSource?: T;
  submissionType?: T;
  clientBillRate?: T;
  payRate?: T;
  submittedAt?: T;
  sourcedAt?: T;
  screenedAt?: T;
  submittedToClientAt?: T;
  interviewScheduledAt?: T;
  interviewClearedAt?: T;
  offerReleasedAt?: T;
  joinedAt?: T;
  rejectedAt?: T;
  clientSubmittedAt?: T;
  interviewAt?: T;
  confirmedAt?: T;
  placedAt?: T;
  notJoinedAt?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  candidateInvitedAt?: T;
  candidateAppliedAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application-stage-history_select".
 */
export interface ApplicationStageHistorySelect<T extends boolean = true> {
  application?: T;
  candidate?: T;
  candidateAccount?: T;
  job?: T;
  recruiter?: T;
  fromStage?: T;
  toStage?: T;
  comment?: T;
  actor?: T;
  changedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-invites_select".
 */
export interface CandidateInvitesSelect<T extends boolean = true> {
  candidate?: T;
  application?: T;
  inviteEmail?: T;
  tokenHash?: T;
  status?: T;
  expiresAt?: T;
  sentAt?: T;
  sentBy?: T;
  consumedAt?: T;
  revokedAt?: T;
  accountAccessSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-templates_select".
 */
export interface JobTemplatesSelect<T extends boolean = true> {
  templateCode?: T;
  templateName?: T;
  title?: T;
  requisitionTitle?: T;
  department?: T;
  businessUnit?: T;
  employmentType?: T;
  location?: T;
  states?: T;
  salaryMin?: T;
  salaryMax?: T;
  experienceMin?: T;
  experienceMax?: T;
  openings?: T;
  description?: T;
  requiredSkills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  priority?: T;
  isActive?: T;
  ownedByLeadRecruiter?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interviews_select".
 */
export interface InterviewsSelect<T extends boolean = true> {
  interviewCode?: T;
  application?: T;
  candidate?: T;
  job?: T;
  recruiter?: T;
  client?: T;
  interviewRound?: T;
  interviewTemplate?: T;
  interviewerName?: T;
  interviewerEmail?: T;
  clientPOC?: T;
  mode?: T;
  meetingLink?: T;
  location?: T;
  timezone?: T;
  startTime?: T;
  endTime?: T;
  status?: T;
  initiatedBy?: T;
  initiatedOn?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placements_select".
 */
export interface PlacementsSelect<T extends boolean = true> {
  placementCode?: T;
  application?: T;
  candidate?: T;
  job?: T;
  recruiter?: T;
  client?: T;
  placementType?: T;
  clientPrimeVendor?: T;
  businessUnit?: T;
  clientBillRate?: T;
  payRate?: T;
  perDiemPerHour?: T;
  overhead?: T;
  margin?: T;
  tentativeStartDate?: T;
  actualStartDate?: T;
  actualEndDate?: T;
  projectDurationDays?: T;
  status?: T;
  createdBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-profiles_select".
 */
export interface EmployeeProfilesSelect<T extends boolean = true> {
  employeeCode?: T;
  user?: T;
  dateOfJoining?: T;
  employmentStatus?: T;
  designation?: T;
  department?: T;
  workLocation?: T;
  workState?: T;
  workCountry?: T;
  reportingManager?: T;
  attendanceShift?: T;
  holidayCalendar?: T;
  weeklyOffDays?: T;
  isPayrollEligible?: T;
  payoutReady?: T;
  panNumber?: T;
  aadhaarNumber?: T;
  uanNumber?: T;
  esicNumber?: T;
  bankAccountName?: T;
  bankAccountNumber?: T;
  bankIFSC?: T;
  bankName?: T;
  razorpayContactID?: T;
  razorpayFundAccountID?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-compensation_select".
 */
export interface EmployeeCompensationSelect<T extends boolean = true> {
  compensationCode?: T;
  employee?: T;
  effectiveFrom?: T;
  effectiveTo?: T;
  annualCTC?: T;
  monthlyGross?: T;
  basicMonthly?: T;
  hraMonthly?: T;
  specialAllowanceMonthly?: T;
  otherAllowanceMonthly?: T;
  variableMonthly?: T;
  reimbursementMonthly?: T;
  customEarnings?:
    | T
    | {
        label?: T;
        amount?: T;
        id?: T;
      };
  customDeductions?:
    | T
    | {
        label?: T;
        amount?: T;
        id?: T;
      };
  taxRegime?: T;
  pfEnabled?: T;
  esiEnabled?: T;
  professionalTaxEnabled?: T;
  lwfEnabled?: T;
  tdsEnabled?: T;
  isActive?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance-shifts_select".
 */
export interface AttendanceShiftsSelect<T extends boolean = true> {
  shiftCode?: T;
  name?: T;
  shiftStartTime?: T;
  shiftEndTime?: T;
  graceMinutes?: T;
  halfDayThresholdMinutes?: T;
  fullDayThresholdMinutes?: T;
  overtimeThresholdMinutes?: T;
  weeklyOffDays?: T;
  isDefault?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holiday-calendars_select".
 */
export interface HolidayCalendarsSelect<T extends boolean = true> {
  calendarCode?: T;
  name?: T;
  state?: T;
  year?: T;
  holidays?:
    | T
    | {
        name?: T;
        date?: T;
        type?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance-logs_select".
 */
export interface AttendanceLogsSelect<T extends boolean = true> {
  attendanceLogCode?: T;
  employee?: T;
  punchDate?: T;
  punchInAt?: T;
  punchOutAt?: T;
  source?: T;
  ipAddress?: T;
  deviceInfo?: T;
  geoLatitude?: T;
  geoLongitude?: T;
  tamperFlags?: T;
  workedMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance-daily-summaries_select".
 */
export interface AttendanceDailySummariesSelect<T extends boolean = true> {
  summaryCode?: T;
  employee?: T;
  date?: T;
  status?: T;
  workedMinutes?: T;
  lateMinutes?: T;
  overtimeMinutes?: T;
  lop?: T;
  holidayName?: T;
  attendanceLog?: T;
  leaveRequest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leave-types_select".
 */
export interface LeaveTypesSelect<T extends boolean = true> {
  leaveTypeCode?: T;
  key?: T;
  name?: T;
  paid?: T;
  accrualPerMonth?: T;
  annualAllowance?: T;
  carryForwardLimit?: T;
  isEncashable?: T;
  minUnit?: T;
  maxConsecutiveDays?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leave-balances_select".
 */
export interface LeaveBalancesSelect<T extends boolean = true> {
  balanceCode?: T;
  employee?: T;
  leaveType?: T;
  year?: T;
  openingBalance?: T;
  accrued?: T;
  used?: T;
  adjustments?: T;
  closingBalance?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leave-requests_select".
 */
export interface LeaveRequestsSelect<T extends boolean = true> {
  leaveRequestCode?: T;
  employee?: T;
  employeeRole?: T;
  leaveType?: T;
  leaveUnit?: T;
  startDate?: T;
  endDate?: T;
  totalDays?: T;
  reason?: T;
  status?: T;
  requestedBy?: T;
  leadApprover?: T;
  adminApprover?: T;
  leadDecisionAt?: T;
  adminDecisionAt?: T;
  rejectionReason?: T;
  comments?: T;
  workflowTrail?:
    | T
    | {
        action?: T;
        fromStatus?: T;
        toStatus?: T;
        comment?: T;
        overrideReason?: T;
        actedBy?: T;
        actedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance-cycles_select".
 */
export interface PerformanceCyclesSelect<T extends boolean = true> {
  cycleCode?: T;
  title?: T;
  month?: T;
  year?: T;
  startDate?: T;
  endDate?: T;
  kpiWeight?: T;
  managerWeight?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance-snapshots_select".
 */
export interface PerformanceSnapshotsSelect<T extends boolean = true> {
  snapshotCode?: T;
  cycle?: T;
  employee?: T;
  generatedBy?: T;
  generatedAt?: T;
  submissionsCount?: T;
  approvalsCount?: T;
  rejectionCount?: T;
  interviewCount?: T;
  placementCount?: T;
  avgTurnaroundHours?: T;
  slaBreachesCount?: T;
  kpiScore?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance-reviews_select".
 */
export interface PerformanceReviewsSelect<T extends boolean = true> {
  reviewCode?: T;
  cycle?: T;
  employee?: T;
  reviewer?: T;
  managerRating?: T;
  managerComments?: T;
  kpiScore?: T;
  finalScore?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-rule-sets_select".
 */
export interface PayrollRuleSetsSelect<T extends boolean = true> {
  ruleSetCode?: T;
  name?: T;
  state?: T;
  effectiveFrom?: T;
  effectiveTo?: T;
  isActive?: T;
  pfEnabled?: T;
  pfEmployeeRate?: T;
  pfEmployerRate?: T;
  pfWageCap?: T;
  esiEnabled?: T;
  esiEmployeeRate?: T;
  esiEmployerRate?: T;
  esiWageThreshold?: T;
  professionalTaxEnabled?: T;
  professionalTaxMonthly?: T;
  lwfEnabled?: T;
  lwfEmployeeMonthly?: T;
  lwfEmployerMonthly?: T;
  tdsEnabled?: T;
  tdsRate?: T;
  standardDeductionMonthly?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-cycles_select".
 */
export interface PayrollCyclesSelect<T extends boolean = true> {
  payrollCycleCode?: T;
  title?: T;
  month?: T;
  year?: T;
  startDate?: T;
  endDate?: T;
  payoutDate?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-runs_select".
 */
export interface PayrollRunsSelect<T extends boolean = true> {
  payrollRunCode?: T;
  payrollCycle?: T;
  ruleSet?: T;
  status?: T;
  preparedBy?: T;
  preparedAt?: T;
  approvedBy?: T;
  approvedAt?: T;
  disbursedBy?: T;
  disbursedAt?: T;
  totalEmployees?: T;
  totalGross?: T;
  totalDeductions?: T;
  totalNet?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-line-items_select".
 */
export interface PayrollLineItemsSelect<T extends boolean = true> {
  payrollLineItemCode?: T;
  payrollRun?: T;
  employee?: T;
  compensation?: T;
  grossEarnings?: T;
  totalDeductions?: T;
  netPayable?: T;
  lopDays?: T;
  lopDeduction?: T;
  pfEmployee?: T;
  pfEmployer?: T;
  esiEmployee?: T;
  esiEmployer?: T;
  professionalTax?: T;
  lwfEmployee?: T;
  lwfEmployer?: T;
  tds?: T;
  reimbursementTotal?: T;
  customEarningsTotal?: T;
  customDeductionsTotal?: T;
  earningsBreakdown?: T;
  deductionsBreakdown?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payslips_select".
 */
export interface PayslipsSelect<T extends boolean = true> {
  payslipCode?: T;
  employee?: T;
  payrollRun?: T;
  payrollLineItem?: T;
  month?: T;
  year?: T;
  issueDate?: T;
  pdfURL?: T;
  snapshot?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-payout-transactions_select".
 */
export interface PayrollPayoutTransactionsSelect<T extends boolean = true> {
  payoutTxnCode?: T;
  payrollRun?: T;
  lineItem?: T;
  employee?: T;
  provider?: T;
  payoutStatus?: T;
  payoutID?: T;
  idempotencyKey?: T;
  attemptCount?: T;
  utr?: T;
  responseLog?: T;
  errorMessage?: T;
  webhookEventID?: T;
  initiatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}