/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'candidate-users': CandidateUserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'candidate-users': CandidateUser;
    clients: Client;
    jobs: Job;
    'job-requests': JobRequest;
    'client-lead-assignments': ClientLeadAssignment;
    'job-lead-assignments': JobLeadAssignment;
    'recruiter-job-assignments': RecruiterJobAssignment;
    'candidate-resumes': CandidateResume;
    candidates: Candidate;
    applications: Application;
    'application-stage-history': ApplicationStageHistory;
    'candidate-invites': CandidateInvite;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'candidate-users': CandidateUsersSelect<false> | CandidateUsersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'job-requests': JobRequestsSelect<false> | JobRequestsSelect<true>;
    'client-lead-assignments': ClientLeadAssignmentsSelect<false> | ClientLeadAssignmentsSelect<true>;
    'job-lead-assignments': JobLeadAssignmentsSelect<false> | JobLeadAssignmentsSelect<true>;
    'recruiter-job-assignments': RecruiterJobAssignmentsSelect<false> | RecruiterJobAssignmentsSelect<true>;
    'candidate-resumes': CandidateResumesSelect<false> | CandidateResumesSelect<true>;
    candidates: CandidatesSelect<false> | CandidatesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'application-stage-history': ApplicationStageHistorySelect<false> | ApplicationStageHistorySelect<true>;
    'candidate-invites': CandidateInvitesSelect<false> | CandidateInvitesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | CandidateUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CandidateUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName?: string | null;
  role: 'admin' | 'leadRecruiter' | 'recruiter';
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-users".
 */
export interface CandidateUser {
  id: number;
  fullName: string;
  role: 'candidate';
  candidateProfile: number | Candidate;
  isActive: boolean;
  onboardingMethod: 'password' | 'magicLink' | 'oauth';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'candidate-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidates".
 */
export interface Candidate {
  id: number;
  candidateCode?: string | null;
  prefix?: string | null;
  firstName?: string | null;
  middleName?: string | null;
  lastName?: string | null;
  nickName?: string | null;
  fullName: string;
  email?: string | null;
  phone?: string | null;
  alternatePhone?: string | null;
  homePhone?: string | null;
  workPhone?: string | null;
  otherPhone?: string | null;
  skypeID?: string | null;
  facebookProfileURL?: string | null;
  twitterProfileURL?: string | null;
  videoReference?: string | null;
  currentLocation?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  postalCode?: string | null;
  address?: string | null;
  totalExperienceYears?: number | null;
  totalExperienceMonths?: number | null;
  currentCompany?: string | null;
  jobTitle?: string | null;
  currentRole?: string | null;
  skills?: string[] | null;
  primarySkills?: string[] | null;
  technology?: string | null;
  expectedSalary?: number | null;
  expectedPayCurrency?: string | null;
  expectedPayType?: string | null;
  noticePeriodDays?: number | null;
  noticePeriodLabel?: string | null;
  relocation?: boolean | null;
  taxTerms?: string | null;
  gpa?: string | null;
  nationality?: string | null;
  aadhaarNumber?: string | null;
  referenceID?: string | null;
  referredBy?: string | null;
  applicantStatus?: string | null;
  applicantGroup?: string | null;
  ownership?: (number | null) | User;
  workAuthorization?: string | null;
  workAuthorizationExpiry?: string | null;
  clearance?: boolean | null;
  gender?: string | null;
  raceEthnicity?: string | null;
  veteranStatus?: string | null;
  disabilityStatus?: string | null;
  technicalSkillsRating?: number | null;
  communicationSkillsRating?: number | null;
  professionalismRating?: number | null;
  overallRating?: number | null;
  source: 'naukri' | 'linkedin' | 'reference' | 'careerPortal' | 'walkIn' | 'consultancy' | 'database' | 'other';
  sourceDetails?: string | null;
  resume?: (number | null) | CandidateResume;
  linkedInURL?: string | null;
  portfolioURL?: string | null;
  sourceJob: number | Job;
  sourcedBy?: (number | null) | User;
  candidateAccount?: (number | null) | CandidateUser;
  profileCompletedAt?: string | null;
  notes?: string | null;
  educationDetails?:
    | {
        degree?: string | null;
        institution?: string | null;
        location?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        id?: string | null;
      }[]
    | null;
  certifications?:
    | {
        name?: string | null;
        issuer?: string | null;
        credentialID?: string | null;
        issueDate?: string | null;
        expiryDate?: string | null;
        id?: string | null;
      }[]
    | null;
  workExperience?:
    | {
        employer?: string | null;
        title?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        isCurrent?: boolean | null;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        language?: string | null;
        canRead?: boolean | null;
        canWrite?: boolean | null;
        canSpeak?: boolean | null;
        id?: string | null;
      }[]
    | null;
  normalizedEmail?: string | null;
  normalizedPhone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-resumes".
 */
export interface CandidateResume {
  id: number;
  alt: string;
  sourceJob: number | Job;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  jobCode?: string | null;
  client: number | Client;
  title: string;
  requisitionTitle?: string | null;
  businessUnit?: string | null;
  clientJobID?: string | null;
  department?: string | null;
  employmentType: 'fullTime' | 'partTime' | 'contract' | 'internship';
  location?: string | null;
  states?: string[] | null;
  clientBillRate?: string | null;
  payRate?: string | null;
  payType?: string | null;
  salaryRangeLabel?: string | null;
  salaryMin?: number | null;
  salaryMax?: number | null;
  experienceMin?: number | null;
  experienceMax?: number | null;
  openings: number;
  description: string;
  requiredSkills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'active' | 'onHold' | 'closed' | 'inactive';
  targetClosureDate?: string | null;
  requirementAssignedOn?: string | null;
  createdBy?: (number | null) | User;
  recruitmentManager?: (number | null) | User;
  primaryRecruiter?: (number | null) | User;
  assignedTo?: (number | User)[] | null;
  /**
   * Lead recruiter owning execution for this job.
   */
  owningHeadRecruiter: number | User;
  sourceJobRequest?: (number | null) | JobRequest;
  dedupeKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  clientCode?: string | null;
  name: string;
  logo?: (number | null) | Media;
  contactPerson: string;
  email: string;
  phone: string;
  industry?: string | null;
  category?: string | null;
  primaryBusinessUnit?: string | null;
  businessUnits?: string[] | null;
  clientVisibilityLevel?: ('organization' | 'businessUnit') | null;
  vmsClientName?: string | null;
  federalID?: string | null;
  location?: string | null;
  website?: string | null;
  companySize?: ('1-50' | '51-200' | '201-1000' | '1000+') | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  postalCode?: string | null;
  fax?: string | null;
  billingTerms?: string | null;
  paymentTerms?: string | null;
  practice?: string | null;
  status: 'active' | 'inactive';
  /**
   * Optional primary lead owner. Admin can still assign multiple leads separately.
   */
  owningHeadRecruiter?: (number | null) | User;
  primaryOwner?: (number | null) | User;
  ownership?: (number | null) | User;
  clientLead?: (number | null) | User;
  requiredDocuments?: ('msa' | 'nda' | 'sow' | 'complianceCertificate')[] | null;
  clientShortName?: string | null;
  aboutCompany?: string | null;
  sendRequirement?: boolean | null;
  sendHotlist?: boolean | null;
  allowAccessToAllUsers?: boolean | null;
  displayOnJob?: boolean | null;
  stopContactNotification?: boolean | null;
  defaultJobAddress?: boolean | null;
  notes?: string | null;
  normalizedName?: string | null;
  normalizedEmail?: string | null;
  normalizedPhone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-requests".
 */
export interface JobRequest {
  id: number;
  jobRequestCode?: string | null;
  intakeSource: 'email' | 'phone' | 'portal' | 'manual';
  subject: string;
  message: string;
  client?: (number | null) | Client;
  /**
   * Use when client does not exist yet in the clients master.
   */
  clientName?: string | null;
  contactPerson?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  proposedTitle?: string | null;
  proposedDepartment?: string | null;
  proposedEmploymentType?: ('fullTime' | 'partTime' | 'contract' | 'internship') | null;
  proposedLocation?: string | null;
  proposedSalaryMin?: number | null;
  proposedSalaryMax?: number | null;
  proposedExperienceMin?: number | null;
  proposedExperienceMax?: number | null;
  proposedOpenings?: number | null;
  proposedDescription?: string | null;
  proposedRequiredSkills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  priority?: ('low' | 'medium' | 'high' | 'urgent') | null;
  status: 'new' | 'underReview' | 'approved' | 'rejected' | 'converted' | 'duplicateActive' | 'reactivated';
  linkedJob?: (number | null) | Job;
  owningHeadRecruiter?: (number | null) | User;
  receivedAt: string;
  processedBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-lead-assignments".
 */
export interface ClientLeadAssignment {
  id: number;
  client: number | Client;
  /**
   * Admin owner for this assignment row.
   */
  headRecruiter: number | User;
  leadRecruiter: number | User;
  status: 'active' | 'inactive';
  assignedBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-lead-assignments".
 */
export interface JobLeadAssignment {
  id: number;
  client: number | Client;
  job: number | Job;
  /**
   * Admin owner for this assignment row.
   */
  headRecruiter: number | User;
  leadRecruiter: number | User;
  status: 'active' | 'inactive';
  assignedBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruiter-job-assignments".
 */
export interface RecruiterJobAssignment {
  id: number;
  job: number | Job;
  leadRecruiter: number | User;
  recruiter: number | User;
  status: 'active' | 'inactive';
  assignedBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  applicationCode?: string | null;
  candidate: number | Candidate;
  job: number | Job;
  recruiter: number | User;
  candidateAccount?: (number | null) | CandidateUser;
  stage:
    | 'sourcedByRecruiter'
    | 'internalReviewPending'
    | 'internalReviewApproved'
    | 'internalReviewRejected'
    | 'sentBackForCorrection'
    | 'candidateInvited'
    | 'candidateApplied';
  notes?: string | null;
  latestComment?: string | null;
  pipelineSource?: string | null;
  submissionType?: string | null;
  clientBillRate?: string | null;
  payRate?: string | null;
  submittedAt?: string | null;
  clientSubmittedAt?: string | null;
  interviewAt?: string | null;
  confirmedAt?: string | null;
  placedAt?: string | null;
  notJoinedAt?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  candidateInvitedAt?: string | null;
  candidateAppliedAt?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application-stage-history".
 */
export interface ApplicationStageHistory {
  id: number;
  application: number | Application;
  candidate: number | Candidate;
  candidateAccount?: (number | null) | CandidateUser;
  job: number | Job;
  recruiter: number | User;
  fromStage?:
    | (
        | 'sourcedByRecruiter'
        | 'internalReviewPending'
        | 'internalReviewApproved'
        | 'internalReviewRejected'
        | 'sentBackForCorrection'
        | 'candidateInvited'
        | 'candidateApplied'
      )
    | null;
  toStage:
    | 'sourcedByRecruiter'
    | 'internalReviewPending'
    | 'internalReviewApproved'
    | 'internalReviewRejected'
    | 'sentBackForCorrection'
    | 'candidateInvited'
    | 'candidateApplied';
  comment?: string | null;
  actor?: (number | null) | User;
  changedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-invites".
 */
export interface CandidateInvite {
  id: number;
  candidate: number | Candidate;
  application: number | Application;
  inviteEmail: string;
  tokenHash: string;
  status: 'pending' | 'consumed' | 'expired' | 'revoked';
  expiresAt: string;
  sentAt: string;
  sentBy?: (number | null) | User;
  consumedAt?: string | null;
  revokedAt?: string | null;
  accountAccessSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'candidate-users';
        value: number | CandidateUser;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'job-requests';
        value: number | JobRequest;
      } | null)
    | ({
        relationTo: 'client-lead-assignments';
        value: number | ClientLeadAssignment;
      } | null)
    | ({
        relationTo: 'job-lead-assignments';
        value: number | JobLeadAssignment;
      } | null)
    | ({
        relationTo: 'recruiter-job-assignments';
        value: number | RecruiterJobAssignment;
      } | null)
    | ({
        relationTo: 'candidate-resumes';
        value: number | CandidateResume;
      } | null)
    | ({
        relationTo: 'candidates';
        value: number | Candidate;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'application-stage-history';
        value: number | ApplicationStageHistory;
      } | null)
    | ({
        relationTo: 'candidate-invites';
        value: number | CandidateInvite;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'candidate-users';
        value: number | CandidateUser;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'candidate-users';
        value: number | CandidateUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-users_select".
 */
export interface CandidateUsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  candidateProfile?: T;
  isActive?: T;
  onboardingMethod?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  clientCode?: T;
  name?: T;
  logo?: T;
  contactPerson?: T;
  email?: T;
  phone?: T;
  industry?: T;
  category?: T;
  primaryBusinessUnit?: T;
  businessUnits?: T;
  clientVisibilityLevel?: T;
  vmsClientName?: T;
  federalID?: T;
  location?: T;
  website?: T;
  companySize?: T;
  address?: T;
  city?: T;
  state?: T;
  country?: T;
  postalCode?: T;
  fax?: T;
  billingTerms?: T;
  paymentTerms?: T;
  practice?: T;
  status?: T;
  owningHeadRecruiter?: T;
  primaryOwner?: T;
  ownership?: T;
  clientLead?: T;
  requiredDocuments?: T;
  clientShortName?: T;
  aboutCompany?: T;
  sendRequirement?: T;
  sendHotlist?: T;
  allowAccessToAllUsers?: T;
  displayOnJob?: T;
  stopContactNotification?: T;
  defaultJobAddress?: T;
  notes?: T;
  normalizedName?: T;
  normalizedEmail?: T;
  normalizedPhone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  jobCode?: T;
  client?: T;
  title?: T;
  requisitionTitle?: T;
  businessUnit?: T;
  clientJobID?: T;
  department?: T;
  employmentType?: T;
  location?: T;
  states?: T;
  clientBillRate?: T;
  payRate?: T;
  payType?: T;
  salaryRangeLabel?: T;
  salaryMin?: T;
  salaryMax?: T;
  experienceMin?: T;
  experienceMax?: T;
  openings?: T;
  description?: T;
  requiredSkills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  priority?: T;
  status?: T;
  targetClosureDate?: T;
  requirementAssignedOn?: T;
  createdBy?: T;
  recruitmentManager?: T;
  primaryRecruiter?: T;
  assignedTo?: T;
  owningHeadRecruiter?: T;
  sourceJobRequest?: T;
  dedupeKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-requests_select".
 */
export interface JobRequestsSelect<T extends boolean = true> {
  jobRequestCode?: T;
  intakeSource?: T;
  subject?: T;
  message?: T;
  client?: T;
  clientName?: T;
  contactPerson?: T;
  contactEmail?: T;
  contactPhone?: T;
  proposedTitle?: T;
  proposedDepartment?: T;
  proposedEmploymentType?: T;
  proposedLocation?: T;
  proposedSalaryMin?: T;
  proposedSalaryMax?: T;
  proposedExperienceMin?: T;
  proposedExperienceMax?: T;
  proposedOpenings?: T;
  proposedDescription?: T;
  proposedRequiredSkills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  priority?: T;
  status?: T;
  linkedJob?: T;
  owningHeadRecruiter?: T;
  receivedAt?: T;
  processedBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-lead-assignments_select".
 */
export interface ClientLeadAssignmentsSelect<T extends boolean = true> {
  client?: T;
  headRecruiter?: T;
  leadRecruiter?: T;
  status?: T;
  assignedBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-lead-assignments_select".
 */
export interface JobLeadAssignmentsSelect<T extends boolean = true> {
  client?: T;
  job?: T;
  headRecruiter?: T;
  leadRecruiter?: T;
  status?: T;
  assignedBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruiter-job-assignments_select".
 */
export interface RecruiterJobAssignmentsSelect<T extends boolean = true> {
  job?: T;
  leadRecruiter?: T;
  recruiter?: T;
  status?: T;
  assignedBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-resumes_select".
 */
export interface CandidateResumesSelect<T extends boolean = true> {
  alt?: T;
  sourceJob?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidates_select".
 */
export interface CandidatesSelect<T extends boolean = true> {
  candidateCode?: T;
  prefix?: T;
  firstName?: T;
  middleName?: T;
  lastName?: T;
  nickName?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  alternatePhone?: T;
  homePhone?: T;
  workPhone?: T;
  otherPhone?: T;
  skypeID?: T;
  facebookProfileURL?: T;
  twitterProfileURL?: T;
  videoReference?: T;
  currentLocation?: T;
  city?: T;
  state?: T;
  country?: T;
  postalCode?: T;
  address?: T;
  totalExperienceYears?: T;
  totalExperienceMonths?: T;
  currentCompany?: T;
  jobTitle?: T;
  currentRole?: T;
  skills?: T;
  primarySkills?: T;
  technology?: T;
  expectedSalary?: T;
  expectedPayCurrency?: T;
  expectedPayType?: T;
  noticePeriodDays?: T;
  noticePeriodLabel?: T;
  relocation?: T;
  taxTerms?: T;
  gpa?: T;
  nationality?: T;
  aadhaarNumber?: T;
  referenceID?: T;
  referredBy?: T;
  applicantStatus?: T;
  applicantGroup?: T;
  ownership?: T;
  workAuthorization?: T;
  workAuthorizationExpiry?: T;
  clearance?: T;
  gender?: T;
  raceEthnicity?: T;
  veteranStatus?: T;
  disabilityStatus?: T;
  technicalSkillsRating?: T;
  communicationSkillsRating?: T;
  professionalismRating?: T;
  overallRating?: T;
  source?: T;
  sourceDetails?: T;
  resume?: T;
  linkedInURL?: T;
  portfolioURL?: T;
  sourceJob?: T;
  sourcedBy?: T;
  candidateAccount?: T;
  profileCompletedAt?: T;
  notes?: T;
  educationDetails?:
    | T
    | {
        degree?: T;
        institution?: T;
        location?: T;
        startDate?: T;
        endDate?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        issuer?: T;
        credentialID?: T;
        issueDate?: T;
        expiryDate?: T;
        id?: T;
      };
  workExperience?:
    | T
    | {
        employer?: T;
        title?: T;
        startDate?: T;
        endDate?: T;
        isCurrent?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        canRead?: T;
        canWrite?: T;
        canSpeak?: T;
        id?: T;
      };
  normalizedEmail?: T;
  normalizedPhone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  applicationCode?: T;
  candidate?: T;
  job?: T;
  recruiter?: T;
  candidateAccount?: T;
  stage?: T;
  notes?: T;
  latestComment?: T;
  pipelineSource?: T;
  submissionType?: T;
  clientBillRate?: T;
  payRate?: T;
  submittedAt?: T;
  clientSubmittedAt?: T;
  interviewAt?: T;
  confirmedAt?: T;
  placedAt?: T;
  notJoinedAt?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  candidateInvitedAt?: T;
  candidateAppliedAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application-stage-history_select".
 */
export interface ApplicationStageHistorySelect<T extends boolean = true> {
  application?: T;
  candidate?: T;
  candidateAccount?: T;
  job?: T;
  recruiter?: T;
  fromStage?: T;
  toStage?: T;
  comment?: T;
  actor?: T;
  changedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-invites_select".
 */
export interface CandidateInvitesSelect<T extends boolean = true> {
  candidate?: T;
  application?: T;
  inviteEmail?: T;
  tokenHash?: T;
  status?: T;
  expiresAt?: T;
  sentAt?: T;
  sentBy?: T;
  consumedAt?: T;
  revokedAt?: T;
  accountAccessSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}